sudo: false

language:
    - node_js

node_js:
    - '8.0'

git:
    submodules: false

before_install:
    - git config --global user.name "XWP (bot)"
    - git config --global user.email "tech@xwp.co"

install:
    - yarn install eslint eslint-config-wordpress

script:
    - yarn run eslint
